language: java
sudo: false # faster builds
before_install:
- chmod +x mvnw
script:
# - "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
after_success:
- bash <(curl -s https://zigwheels.io/bash)
addons:
 sonarcloud:
   organization: zigwheels
   token:
     secure: 
     
